import { createConversationActions } from './conversation-actions.js';
import { createHostLabActions } from './host-lab-actions.js';
import { createShellAccessActions } from './shell-access-actions.js';
import { createShellLoaders } from './shell-loaders.js';
import { createShellViewModels } from './shell-view-models.js';
import { useShellEffects } from './use-shell-effects.js';
import { useShellState } from './use-shell-state.js';
import {
    AuthLoadingScreen,
    AuthUnlockScreen,
} from './components/AuthShell.js';
import { ShellWorkspace } from './components/ShellWorkspace.js';

export function App() {
    const {
        actionError,
        activeRuns,
        authAdminBusy,
        authAllowsDashboard,
        authBusy,
        authSessions,
        authStatus,
        authTokenInput,
        authTokenSummaries,
        browserFormFieldsText,
        browserSubmitSelector,
        browserTarget,
        canManageAuth,
        chats,
        composerText,
        cronState,
        dashboardError,
        deferredComposerText,
        deferredSearchQuery,
        draftChatId,
        editingMessageId,
        editingText,
        executionMode,
        hostActionBusy,
        hostActionResult,
        inspectorTab,
        lastRun,
        latestManagedToken,
        managedTokenId,
        managedTokenScopes,
        messages,
        pairingBusy,
        pairingChannel,
        pairingInvite,
        pairingKind,
        pairingState,
        providerHealth,
        queueSummaries,
        realtimeConnected,
        recentEvents,
        routePreview,
        screenApp,
        screenInputText,
        screenSendClear,
        screenSendInspectAfter,
        screenSendLaunchIfNeeded,
        screenSendPressReturn,
        screenSendRequireFrontmost,
        searchLoading,
        searchQuery,
        searchResults,
        searchScope,
        selectedChatId,
        setActionError,
        setActiveRuns,
        setAuthAdminBusy,
        setAuthBusy,
        setAuthSessions,
        setAuthStatus,
        setAuthTokenInput,
        setAuthTokenSummaries,
        setBrowserFormFieldsText,
        setBrowserSubmitSelector,
        setBrowserTarget,
        setChats,
        setComposerText,
        setCronState,
        setDashboardError,
        setDraftChatId,
        setEditingMessageId,
        setEditingText,
        setExecutionMode,
        setHostActionBusy,
        setHostActionResult,
        setInspectorTab,
        setLastRun,
        setLatestManagedToken,
        setManagedTokenId,
        setManagedTokenScopes,
        setMessages,
        setPairingBusy,
        setPairingChannel,
        setPairingInvite,
        setPairingKind,
        setPairingState,
        setProviderHealth,
        setQueueSummaries,
        setRealtimeConnected,
        setRecentEvents,
        setRoutePreview,
        setScreenApp,
        setScreenInputText,
        setScreenSendClear,
        setScreenSendInspectAfter,
        setScreenSendLaunchIfNeeded,
        setScreenSendPressReturn,
        setScreenSendRequireFrontmost,
        setSearchLoading,
        setSearchQuery,
        setSearchResults,
        setSearchScope,
        setSelectedChatId,
        setStatus,
        setSubmitting,
        setToolLogs,
        status,
        submitting,
        toolLogs,
    } = useShellState();
    const {
        loadAuthAdminPanel,
        loadAuthStatus,
        loadChatList,
        loadMessagesPanel,
        loadPairingPanel,
        loadQueuePanel,
        loadRoutePreview,
        loadSchedulerPanel,
        loadSearch,
        loadShellPanels,
        loadToolLogsPanel,
    } = createShellLoaders({
        draftChatId,
        searchScope,
        selectedChatId,
        setActionError,
        setAuthSessions,
        setAuthStatus,
        setAuthTokenSummaries,
        setChats,
        setCronState,
        setDashboardError,
        setDraftChatId,
        setMessages,
        setPairingState,
        setProviderHealth,
        setQueueSummaries,
        setRoutePreview,
        setSearchLoading,
        setSearchResults,
        setSelectedChatId,
        setStatus,
        setToolLogs,
    });

    useShellEffects({
        authAllowsDashboard,
        deferredComposerText,
        deferredSearchQuery,
        draftChatId,
        loadAuthStatus,
        loadChatList,
        loadMessagesPanel,
        loadQueuePanel,
        loadRoutePreview,
        loadSchedulerPanel,
        loadSearch,
        loadShellPanels,
        loadToolLogsPanel,
        searchScope,
        selectedChatId,
        setActiveRuns,
        setDashboardError,
        setRealtimeConnected,
        setRecentEvents,
    });

    const { handleTaskRun, parseBrowserFormFields, runHostAction } =
        createHostLabActions({
            browserFormFieldsText,
            loadChatList,
            loadSchedulerPanel,
            loadToolLogsPanel,
            selectedChatId,
            setActionError,
            setHostActionBusy,
            setHostActionResult,
        });
    const {
        handleAuthLogin,
        handleAuthLogout,
        handleCreateManagedToken,
        handleCreatePairingInvite,
        handleRevokeAuthSession,
        handleRevokeAuthToken,
        handleRevokePairingGrant,
        handleRevokePairingInvite,
    } = createShellAccessActions({
        authTokenInput,
        loadAuthAdminPanel,
        loadMessagesPanel,
        loadPairingPanel,
        loadShellPanels,
        loadToolLogsPanel,
        managedTokenId,
        managedTokenScopes,
        pairingChannel,
        pairingInvite,
        pairingKind,
        selectedChatId,
        setActionError,
        setActiveRuns,
        setAuthAdminBusy,
        setAuthBusy,
        setAuthStatus,
        setAuthTokenInput,
        setDashboardError,
        setLatestManagedToken,
        setManagedTokenId,
        setMessages,
        setPairingBusy,
        setPairingInvite,
        setRealtimeConnected,
        setRecentEvents,
        setToolLogs,
    });
    const {
        handleCancelRun,
        handleCreateChat,
        handleEditCancel,
        handleEditSave,
        handleEditStart,
        handleInjectIntoComposer,
        handlePrefixAgent,
        handleResend,
        handleRevoke,
        handleSelectChat,
        handleSend,
        handleStartSearch,
    } = createConversationActions({
        composerText,
        editingText,
        executionMode,
        loadChatList,
        loadMessagesPanel,
        loadToolLogsPanel,
        selectedChatId,
        setActionError,
        setComposerText,
        setDraftChatId,
        setEditingMessageId,
        setEditingText,
        setLastRun,
        setMessages,
        setSelectedChatId,
        setSubmitting,
    });

    if (authStatus === null) {
        return <AuthLoadingScreen />;
    }

    if (authStatus.authRequired && !authStatus.authenticated) {
        return (
            <AuthUnlockScreen
                authBusy={authBusy}
                authStatus={authStatus}
                authTokenInput={authTokenInput}
                dashboardError={dashboardError}
                onAuthTokenInputChange={setAuthTokenInput}
                onLogin={() => {
                    void handleAuthLogin();
                }}
            />
        );
    }

    const {
        availableAgents,
        activityInspector,
        chatList,
        composerShowsSearch,
        currentActiveRun,
        editedSuccessorById,
        latestAssistantRoute,
        queueSummaryByChatId,
        runtimeInspector,
        searchInspector,
        selectedChat,
        selectedChatQueue,
        selectedQueueLeadRun,
        totalTasks,
    } = createShellViewModels({
        actionError: setActionError,
        activeRuns,
        authAdminBusy,
        authSessions,
        authTokenSummaries,
        browserFormFieldsText,
        browserSubmitSelector,
        browserTarget,
        canManageAuth,
        chats,
        cronState,
        deferredComposerText,
        deferredSearchQuery,
        draftChatId,
        handleCreateManagedToken,
        handleCreatePairingInvite,
        handleInjectIntoComposer,
        handleRevokeAuthSession,
        handleRevokeAuthToken,
        handleRevokePairingGrant,
        handleRevokePairingInvite,
        handleSelectChat,
        handleTaskRun,
        hostActionBusy,
        hostActionResult,
        latestManagedToken,
        managedTokenId,
        managedTokenScopes,
        messages,
        pairingBusy,
        pairingChannel,
        pairingInvite,
        pairingKind,
        pairingState,
        parseBrowserFormFields,
        providerHealth,
        queueSummaries,
        recentEvents,
        runHostAction,
        screenApp,
        screenInputText,
        screenSendClear,
        screenSendInspectAfter,
        screenSendLaunchIfNeeded,
        screenSendPressReturn,
        screenSendRequireFrontmost,
        searchLoading,
        searchQuery,
        searchResults,
        searchScope,
        selectedChatId,
        setBrowserFormFieldsText,
        setBrowserSubmitSelector,
        setBrowserTarget,
        setInspectorTab,
        setManagedTokenId,
        setManagedTokenScopes,
        setPairingChannel,
        setPairingKind,
        setScreenApp,
        setScreenInputText,
        setScreenSendClear,
        setScreenSendInspectAfter,
        setScreenSendLaunchIfNeeded,
        setScreenSendPressReturn,
        setScreenSendRequireFrontmost,
        setSearchQuery,
        setSearchScope,
        status,
        toolLogs,
    });

    return (
        <ShellWorkspace
            topBar={{
                authBusy,
                authRequired: authStatus.authRequired,
                availableAgentCount: availableAgents.length,
                handleAuthLogout,
                realtimeConnected,
                taskCount: totalTasks,
                threadCount: chatList.length,
                tokenId: authStatus.tokenId,
            }}
            sidebar={{
                availableAgents,
                chatList,
                currentActiveRun,
                handleCreateChat,
                handlePrefixAgent,
                handleSelectChat,
                handleStartSearch,
                latestAssistantRoute,
                queueSummaryByChatId,
                routePreview,
                selectedChat,
                selectedChatId,
                selectedQueueLeadRun,
                serverHost: status?.server.host,
            }}
            conversation={{
                actionError,
                availableAgents,
                composerShowsSearch,
                composerText,
                currentActiveRun,
                dashboardError,
                editedSuccessorById,
                editingMessageId,
                editingText,
                executionMode,
                handleCancelRun,
                handleEditCancel,
                handleEditSave,
                handleEditStart,
                handlePrefixAgent,
                handleResend,
                handleRevoke,
                handleSend,
                handleStartSearch,
                lastRun,
                messages,
                realtimeConnected,
                routePreview,
                selectedChat,
                selectedChatId,
                selectedChatQueue,
                selectedQueueLeadRun,
                setComposerText,
                setEditingText,
                setExecutionMode,
                submitting,
            }}
            inspector={{
                activity: activityInspector,
                inspectorTab,
                runtime: runtimeInspector,
                search: searchInspector,
                setInspectorTab,
            }}
        />
    );
}
