import { createConversationActions } from './conversation-actions.js';
import { createHostLabActions } from './host-lab-actions.js';
import { createShellAccessActions } from './shell-access-actions.js';
import { createShellLoaders } from './shell-loaders.js';
import { createShellViewModels } from './shell-view-models.js';
import { useShellEffects } from './use-shell-effects.js';
import { useShellState } from './use-shell-state.js';
import type { AuthUnlockScreenProps } from './components/AuthShell.js';
import type { ShellWorkspaceProps } from './components/ShellWorkspace.js';

export type ShellControllerState =
    | { kind: 'loading' }
    | { kind: 'unlock'; props: AuthUnlockScreenProps }
    | { kind: 'workspace'; props: ShellWorkspaceProps };

export function useShellController(): ShellControllerState {
    const {
        auth,
        chat,
        hostLab,
        pairing,
        runtime,
        search,
        setters,
        ui,
    } = useShellState();
    const {
        loadAuthAdminPanel,
        loadAuthStatus,
        loadChatList,
        loadMessagesPanel,
        loadPairingPanel,
        loadQueuePanel,
        loadRoutePreview,
        loadSchedulerPanel,
        loadSearch,
        loadShellPanels,
        loadToolLogsPanel,
    } = createShellLoaders({
        draftChatId: chat.draftChatId,
        searchScope: search.scope,
        selectedChatId: chat.selectedChatId,
        setActionError: setters.ui.setActionError,
        setAuthSessions: setters.auth.setSessions,
        setAuthStatus: setters.auth.setStatus,
        setAuthTokenSummaries: setters.auth.setTokenSummaries,
        setChats: setters.chat.setChats,
        setCronState: setters.runtime.setTasks,
        setDashboardError: setters.ui.setDashboardError,
        setDraftChatId: setters.chat.setDraftChatId,
        setMessages: setters.chat.setMessages,
        setPairingState: setters.pairing.setState,
        setProviderHealth: setters.runtime.setProviderHealth,
        setQueueSummaries: setters.runtime.setQueueSummaries,
        setRoutePreview: setters.runtime.setRoutePreview,
        setSearchLoading: setters.search.setLoading,
        setSearchResults: setters.search.setResults,
        setSelectedChatId: setters.chat.setSelectedChatId,
        setStatus: setters.runtime.setStatus,
        setToolLogs: setters.chat.setToolLogs,
    });

    useShellEffects({
        authAllowsDashboard: auth.allowsDashboard,
        deferredComposerText: ui.deferredComposerText,
        deferredSearchQuery: search.deferredQuery,
        draftChatId: chat.draftChatId,
        loadAuthStatus,
        loadChatList,
        loadMessagesPanel,
        loadQueuePanel,
        loadRoutePreview,
        loadSchedulerPanel,
        loadSearch,
        loadShellPanels,
        loadToolLogsPanel,
        searchScope: search.scope,
        selectedChatId: chat.selectedChatId,
        setActiveRuns: setters.runtime.setActiveRuns,
        setDashboardError: setters.ui.setDashboardError,
        setRealtimeConnected: setters.runtime.setRealtimeConnected,
        setRecentEvents: setters.runtime.setRecentEvents,
    });

    const { handleTaskRun, parseBrowserFormFields, runHostAction } =
        createHostLabActions({
            browserFormFieldsText: hostLab.browserFormFieldsText,
            loadChatList,
            loadSchedulerPanel,
            loadToolLogsPanel,
            selectedChatId: chat.selectedChatId,
            setActionError: setters.ui.setActionError,
            setHostActionBusy: setters.hostLab.setHostActionBusy,
            setHostActionResult: setters.hostLab.setHostActionResult,
        });
    const {
        handleAuthLogin,
        handleAuthLogout,
        handleCreateManagedToken,
        handleCreatePairingInvite,
        handleRevokeAuthSession,
        handleRevokeAuthToken,
        handleRevokePairingGrant,
        handleRevokePairingInvite,
    } = createShellAccessActions({
        authTokenInput: auth.tokenInput,
        loadAuthAdminPanel,
        loadMessagesPanel,
        loadPairingPanel,
        loadShellPanels,
        loadToolLogsPanel,
        managedTokenId: auth.managedTokenId,
        managedTokenScopes: auth.managedTokenScopes,
        pairingChannel: pairing.channel,
        pairingInvite: pairing.invite,
        pairingKind: pairing.kind,
        selectedChatId: chat.selectedChatId,
        setActionError: setters.ui.setActionError,
        setActiveRuns: setters.runtime.setActiveRuns,
        setAuthAdminBusy: setters.auth.setAdminBusy,
        setAuthBusy: setters.auth.setBusy,
        setAuthStatus: setters.auth.setStatus,
        setAuthTokenInput: setters.auth.setTokenInput,
        setDashboardError: setters.ui.setDashboardError,
        setLatestManagedToken: setters.auth.setLatestManagedToken,
        setManagedTokenId: setters.auth.setManagedTokenId,
        setMessages: setters.chat.setMessages,
        setPairingBusy: setters.pairing.setBusy,
        setPairingInvite: setters.pairing.setInvite,
        setRealtimeConnected: setters.runtime.setRealtimeConnected,
        setRecentEvents: setters.runtime.setRecentEvents,
        setToolLogs: setters.chat.setToolLogs,
    });
    const {
        handleCancelRun,
        handleCreateChat,
        handleEditCancel,
        handleEditSave,
        handleEditStart,
        handleInjectIntoComposer,
        handlePrefixAgent,
        handleResend,
        handleRevoke,
        handleSelectChat,
        handleSend,
        handleStartSearch,
    } = createConversationActions({
        composerText: chat.composerText,
        editingText: chat.editingText,
        executionMode: chat.executionMode,
        loadChatList,
        loadMessagesPanel,
        loadToolLogsPanel,
        selectedChatId: chat.selectedChatId,
        setActionError: setters.ui.setActionError,
        setComposerText: setters.chat.setComposerText,
        setDraftChatId: setters.chat.setDraftChatId,
        setEditingMessageId: setters.chat.setEditingMessageId,
        setEditingText: setters.chat.setEditingText,
        setLastRun: setters.chat.setLastRun,
        setMessages: setters.chat.setMessages,
        setSelectedChatId: setters.chat.setSelectedChatId,
        setSubmitting: setters.chat.setSubmitting,
    });

    if (auth.status === null) {
        return { kind: 'loading' };
    }

    if (auth.status.authRequired && !auth.status.authenticated) {
        return {
            kind: 'unlock',
            props: {
                authBusy: auth.busy,
                authStatus: auth.status,
                authTokenInput: auth.tokenInput,
                dashboardError: ui.dashboardError,
                onAuthTokenInputChange: setters.auth.setTokenInput,
                onLogin: () => {
                    void handleAuthLogin();
                },
            },
        };
    }

    const {
        availableAgents,
        activityInspector,
        chatList,
        composerShowsSearch,
        currentActiveRun,
        editedSuccessorById,
        latestAssistantRoute,
        queueSummaryByChatId,
        runtimeInspector,
        searchInspector,
        selectedChat,
        selectedChatQueue,
        selectedQueueLeadRun,
        totalTasks,
    } = createShellViewModels({
        actionError: setters.ui.setActionError,
        activeRuns: runtime.activeRuns,
        authAdminBusy: auth.adminBusy,
        authSessions: auth.sessions,
        authTokenSummaries: auth.tokenSummaries,
        browserFormFieldsText: hostLab.browserFormFieldsText,
        browserSubmitSelector: hostLab.browserSubmitSelector,
        browserTarget: hostLab.browserTarget,
        canManageAuth: auth.canManageAuth,
        chats: chat.chats,
        cronState: runtime.tasks,
        deferredComposerText: ui.deferredComposerText,
        deferredSearchQuery: search.deferredQuery,
        draftChatId: chat.draftChatId,
        handleCreateManagedToken,
        handleCreatePairingInvite,
        handleInjectIntoComposer,
        handleRevokeAuthSession,
        handleRevokeAuthToken,
        handleRevokePairingGrant,
        handleRevokePairingInvite,
        handleSelectChat,
        handleTaskRun,
        hostActionBusy: hostLab.hostActionBusy,
        hostActionResult: hostLab.hostActionResult,
        latestManagedToken: auth.latestManagedToken,
        managedTokenId: auth.managedTokenId,
        managedTokenScopes: auth.managedTokenScopes,
        messages: chat.messages,
        pairingBusy: pairing.busy,
        pairingChannel: pairing.channel,
        pairingInvite: pairing.invite,
        pairingKind: pairing.kind,
        pairingState: pairing.state,
        parseBrowserFormFields,
        providerHealth: runtime.providerHealth,
        queueSummaries: runtime.queueSummaries,
        recentEvents: runtime.recentEvents,
        runHostAction,
        screenApp: hostLab.screenApp,
        screenInputText: hostLab.screenInputText,
        screenSendClear: hostLab.screenSendClear,
        screenSendInspectAfter: hostLab.screenSendInspectAfter,
        screenSendLaunchIfNeeded: hostLab.screenSendLaunchIfNeeded,
        screenSendPressReturn: hostLab.screenSendPressReturn,
        screenSendRequireFrontmost: hostLab.screenSendRequireFrontmost,
        searchLoading: search.loading,
        searchQuery: search.query,
        searchResults: search.results,
        searchScope: search.scope,
        selectedChatId: chat.selectedChatId,
        setBrowserFormFieldsText: setters.hostLab.setBrowserFormFieldsText,
        setBrowserSubmitSelector: setters.hostLab.setBrowserSubmitSelector,
        setBrowserTarget: setters.hostLab.setBrowserTarget,
        setInspectorTab: setters.ui.setInspectorTab,
        setManagedTokenId: setters.auth.setManagedTokenId,
        setManagedTokenScopes: setters.auth.setManagedTokenScopes,
        setPairingChannel: setters.pairing.setChannel,
        setPairingKind: setters.pairing.setKind,
        setScreenApp: setters.hostLab.setScreenApp,
        setScreenInputText: setters.hostLab.setScreenInputText,
        setScreenSendClear: setters.hostLab.setScreenSendClear,
        setScreenSendInspectAfter: setters.hostLab.setScreenSendInspectAfter,
        setScreenSendLaunchIfNeeded: setters.hostLab.setScreenSendLaunchIfNeeded,
        setScreenSendPressReturn: setters.hostLab.setScreenSendPressReturn,
        setScreenSendRequireFrontmost: setters.hostLab.setScreenSendRequireFrontmost,
        setSearchQuery: setters.search.setQuery,
        setSearchScope: setters.search.setScope,
        status: runtime.status,
        toolLogs: chat.toolLogs,
    });

    return {
        kind: 'workspace',
        props: {
            topBar: {
                authBusy: auth.busy,
                authRequired: auth.status.authRequired,
                availableAgentCount: availableAgents.length,
                handleAuthLogout,
                realtimeConnected: runtime.realtimeConnected,
                taskCount: totalTasks,
                threadCount: chatList.length,
                tokenId: auth.status.tokenId,
            },
            sidebar: {
                availableAgents,
                chatList,
                currentActiveRun,
                handleCreateChat,
                handlePrefixAgent,
                handleSelectChat,
                handleStartSearch,
                latestAssistantRoute,
                queueSummaryByChatId,
                routePreview: runtime.routePreview,
                selectedChat,
                selectedChatId: chat.selectedChatId,
                selectedQueueLeadRun,
                serverHost: runtime.status?.server.host,
            },
            conversation: {
                actionError: ui.actionError,
                availableAgents,
                composerShowsSearch,
                composerText: chat.composerText,
                currentActiveRun,
                dashboardError: ui.dashboardError,
                editedSuccessorById,
                editingMessageId: chat.editingMessageId,
                editingText: chat.editingText,
                executionMode: chat.executionMode,
                handleCancelRun,
                handleEditCancel,
                handleEditSave,
                handleEditStart,
                handlePrefixAgent,
                handleResend,
                handleRevoke,
                handleSend,
                handleStartSearch,
                lastRun: chat.lastRun,
                messages: chat.messages,
                realtimeConnected: runtime.realtimeConnected,
                routePreview: runtime.routePreview,
                selectedChat,
                selectedChatId: chat.selectedChatId,
                selectedChatQueue,
                selectedQueueLeadRun,
                setComposerText: setters.chat.setComposerText,
                setEditingText: setters.chat.setEditingText,
                setExecutionMode: setters.chat.setExecutionMode,
                submitting: chat.submitting,
            },
            inspector: {
                activity: activityInspector,
                inspectorTab: ui.inspectorTab,
                runtime: runtimeInspector,
                search: searchInspector,
                setInspectorTab: setters.ui.setInspectorTab,
            },
        },
    };
}
